services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    
    environment:
      MYSQL_ROOT_PASSWORD: cases123

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./webapp
      dockerfile: Dockerfile

    depends_on:
      - db

    command: python server.py
    
    environment:
      database: localhost
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: cases123
      DB_NAME: cases

    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app

volumes:
  db_data:
  web_data: